### ISSUE TITLE
Need permissions to push new branch

### ISSUE THREAD

**Issue by FreeScholar** [rahulbaisane/telepathynetwork#1]
@rahulbaisane

From my prompt:
git push --set-upstream origin micky

freescholar@rascal:/srv/projects/telepathynetwork$ git push --set-upstream origin micky
ERROR: Permission to rahulbaisane/telepathynetwork.git denied to FreeScholar.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
freescholar@rascal:/srv/projects/telepathynetwork$ git checkout master
M	vendor/composer/ClassLoader.php
M	vendor/composer/autoload_classmap.php
M	vendor/composer/autoload_files.php
M	vendor/composer/autoload_namespaces.php
M	vendor/composer/autoload_psr4.php
M	vendor/composer/autoload_static.php
M	vendor/composer/installed.json
Switched to branch 'master'

**Comment by rahulbaisane** [comment]
Temporary closing this issue.
